# ============================================================
# SkyRoute Airlines - Baggage Fee Calculator
# Configuración de la aplicación Spring Boot
# ============================================================

spring.application.name=skyroute-service

# Puerto del servidor embebido (deshabilitado para examen de pruebas unitarias)
spring.main.web-application-type=none

# Logging
logging.level.root=WARN
logging.level.ec.edu.epn=INFO
